# -*- coding: utf-8 -*-
"""constant_tensors_and_variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12PFURULS6FRVy0toVjZHRgdyLwdVRQG8

Listing 3.1: All-ones or all-zeros tensors
"""

import tensorflow as tf
x = tf.ones(shape=(2,1))
print(x)

"""
tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
"""

x = tf.zeros(shape=(2,1))
print(x)
"""
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)
"""

"""Listing 3.2: Random tensors"""

x = tf.random.normal(shape=(3,1), mean=0., stddev=1.)
# Tensor of random values drawn from a normal distribution with mean 0 and standard deviation 1.
print(x)
"""
tf.Tensor(
[[0.09287316]
 [0.00621388]
 [1.0607849 ]], shape=(3, 1), dtype=float32)
"""

x = tf.random.uniform(shape=(3,1), minval=0., maxval=1.)
# Tensor of random values from a uniform distribution between 0 and 1
print(x)
"""
tf.Tensor(
[[0.96023655]
 [0.73357785]
 [0.28952456]], shape=(3, 1), dtype=float32)
"""

"""Listing 3.3: NumPy arrays are assignable"""

import numpy as np
x = np.ones(shape=(2,2))
x[0,0] = 0.

"""Listing 3.4: TensorFlow tensors are not assignable"""

x = tf.ones(shape=(2,2))
x[0,0] = 0.
# TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

"""Listing 3.5: Creating a TensorFlow variable"""

v = tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
print(v)
"""
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.41559955],
       [-0.9826106 ],
       [-0.51114005]], dtype=float32)>
"""

"""Listing 3.6: Assigning a value to a TensorFlow variable"""

v.assign(tf.ones((3,1)))
"""
<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>
"""

"""Listing 3.7: Assigning a value to a subset of a TensorFlow variable"""

v[0,0].assign(3.)
"""
<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>
"""

"""Listing 3.8: Using assign_add()"""

v.assign_add(tf.ones((3,1)))
# assign_add +=
# assign_sub -=
"""
<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>
"""

"""Listing 3.9: A few basic math operations"""

a = tf.ones((2,2))
b = tf.square(a)
print(b)
"""
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32
"""
c = tf.sqrt(a)
print(c)
"""
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
"""

d = b+c
print(d)
"""
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
"""

e = tf.matmul(a, b)
print(e)
"""
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
"""

e*=d
print(e)
"""
tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)
"""

